; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=loop-vectorize -mtriple=arm64-apple-ios -S -mcpu=cyclone -enable-interleaved-mem-accesses=false < %s | FileCheck %s
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-n32:64-S128"

@kernel = global [512 x float] zeroinitializer, align 16
@kernel2 = global [512 x float] zeroinitializer, align 16
@kernel3 = global [512 x float] zeroinitializer, align 16
@kernel4 = global [512 x float] zeroinitializer, align 16
@src_data = global [1536 x float] zeroinitializer, align 16
@r_ = global i8 0, align 1
@g_ = global i8 0, align 1
@b_ = global i8 0, align 1

; The cost of gathers in the loop gets offset by the vector math.

define void @_Z4testmm(i64 %size, i64 %offset) {
; CHECK-LABEL: define void @_Z4testmm(
; CHECK-SAME: i64 [[SIZE:%.*]], i64 [[OFFSET:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP53:%.*]] = icmp eq i64 [[SIZE]], 0
; CHECK-NEXT:    br i1 [[CMP53]], label %[[FOR_END:.*]], label %[[FOR_BODY_LR_PH:.*]]
; CHECK:       [[FOR_BODY_LR_PH]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[SIZE]], 8
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[SIZE]], 8
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[SIZE]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <4 x float> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP68:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x float> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP69:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI2:%.*]] = phi <4 x float> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP110:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI3:%.*]] = phi <4 x float> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP111:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI4:%.*]] = phi <4 x float> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP152:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI5:%.*]] = phi <4 x float> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP153:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP3:%.*]] = add i64 [[INDEX]], 3
; CHECK-NEXT:    [[TMP4:%.*]] = add i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = add i64 [[INDEX]], 5
; CHECK-NEXT:    [[TMP6:%.*]] = add i64 [[INDEX]], 6
; CHECK-NEXT:    [[TMP7:%.*]] = add i64 [[INDEX]], 7
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 [[TMP0]], [[OFFSET]]
; CHECK-NEXT:    [[TMP9:%.*]] = add i64 [[TMP1]], [[OFFSET]]
; CHECK-NEXT:    [[TMP10:%.*]] = add i64 [[TMP2]], [[OFFSET]]
; CHECK-NEXT:    [[TMP11:%.*]] = add i64 [[TMP3]], [[OFFSET]]
; CHECK-NEXT:    [[TMP12:%.*]] = add i64 [[TMP4]], [[OFFSET]]
; CHECK-NEXT:    [[TMP13:%.*]] = add i64 [[TMP5]], [[OFFSET]]
; CHECK-NEXT:    [[TMP14:%.*]] = add i64 [[TMP6]], [[OFFSET]]
; CHECK-NEXT:    [[TMP15:%.*]] = add i64 [[TMP7]], [[OFFSET]]
; CHECK-NEXT:    [[TMP16:%.*]] = mul i64 [[TMP8]], 3
; CHECK-NEXT:    [[TMP17:%.*]] = mul i64 [[TMP9]], 3
; CHECK-NEXT:    [[TMP18:%.*]] = mul i64 [[TMP10]], 3
; CHECK-NEXT:    [[TMP19:%.*]] = mul i64 [[TMP11]], 3
; CHECK-NEXT:    [[TMP20:%.*]] = mul i64 [[TMP12]], 3
; CHECK-NEXT:    [[TMP21:%.*]] = mul i64 [[TMP13]], 3
; CHECK-NEXT:    [[TMP22:%.*]] = mul i64 [[TMP14]], 3
; CHECK-NEXT:    [[TMP23:%.*]] = mul i64 [[TMP15]], 3
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP16]]
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP17]]
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP18]]
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP19]]
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP20]]
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP21]]
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP22]]
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP23]]
; CHECK-NEXT:    [[TMP32:%.*]] = load float, ptr [[TMP24]], align 4
; CHECK-NEXT:    [[TMP33:%.*]] = load float, ptr [[TMP25]], align 4
; CHECK-NEXT:    [[TMP34:%.*]] = load float, ptr [[TMP26]], align 4
; CHECK-NEXT:    [[TMP35:%.*]] = load float, ptr [[TMP27]], align 4
; CHECK-NEXT:    [[TMP36:%.*]] = insertelement <4 x float> poison, float [[TMP32]], i32 0
; CHECK-NEXT:    [[TMP37:%.*]] = insertelement <4 x float> [[TMP36]], float [[TMP33]], i32 1
; CHECK-NEXT:    [[TMP38:%.*]] = insertelement <4 x float> [[TMP37]], float [[TMP34]], i32 2
; CHECK-NEXT:    [[TMP39:%.*]] = insertelement <4 x float> [[TMP38]], float [[TMP35]], i32 3
; CHECK-NEXT:    [[TMP40:%.*]] = load float, ptr [[TMP28]], align 4
; CHECK-NEXT:    [[TMP41:%.*]] = load float, ptr [[TMP29]], align 4
; CHECK-NEXT:    [[TMP42:%.*]] = load float, ptr [[TMP30]], align 4
; CHECK-NEXT:    [[TMP43:%.*]] = load float, ptr [[TMP31]], align 4
; CHECK-NEXT:    [[TMP44:%.*]] = insertelement <4 x float> poison, float [[TMP40]], i32 0
; CHECK-NEXT:    [[TMP45:%.*]] = insertelement <4 x float> [[TMP44]], float [[TMP41]], i32 1
; CHECK-NEXT:    [[TMP46:%.*]] = insertelement <4 x float> [[TMP45]], float [[TMP42]], i32 2
; CHECK-NEXT:    [[TMP47:%.*]] = insertelement <4 x float> [[TMP46]], float [[TMP43]], i32 3
; CHECK-NEXT:    [[TMP48:%.*]] = getelementptr inbounds [512 x float], ptr @kernel, i64 0, i64 [[TMP0]]
; CHECK-NEXT:    [[TMP49:%.*]] = getelementptr inbounds float, ptr [[TMP48]], i32 0
; CHECK-NEXT:    [[TMP50:%.*]] = getelementptr inbounds float, ptr [[TMP48]], i32 4
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x float>, ptr [[TMP49]], align 4
; CHECK-NEXT:    [[WIDE_LOAD6:%.*]] = load <4 x float>, ptr [[TMP50]], align 4
; CHECK-NEXT:    [[TMP51:%.*]] = fmul fast <4 x float> [[TMP39]], [[WIDE_LOAD]]
; CHECK-NEXT:    [[TMP52:%.*]] = fmul fast <4 x float> [[TMP47]], [[WIDE_LOAD6]]
; CHECK-NEXT:    [[TMP53:%.*]] = getelementptr inbounds [512 x float], ptr @kernel2, i64 0, i64 [[TMP0]]
; CHECK-NEXT:    [[TMP54:%.*]] = getelementptr inbounds float, ptr [[TMP53]], i32 0
; CHECK-NEXT:    [[TMP55:%.*]] = getelementptr inbounds float, ptr [[TMP53]], i32 4
; CHECK-NEXT:    [[WIDE_LOAD7:%.*]] = load <4 x float>, ptr [[TMP54]], align 4
; CHECK-NEXT:    [[WIDE_LOAD8:%.*]] = load <4 x float>, ptr [[TMP55]], align 4
; CHECK-NEXT:    [[TMP56:%.*]] = fmul fast <4 x float> [[TMP51]], [[WIDE_LOAD7]]
; CHECK-NEXT:    [[TMP57:%.*]] = fmul fast <4 x float> [[TMP52]], [[WIDE_LOAD8]]
; CHECK-NEXT:    [[TMP58:%.*]] = getelementptr inbounds [512 x float], ptr @kernel3, i64 0, i64 [[TMP0]]
; CHECK-NEXT:    [[TMP59:%.*]] = getelementptr inbounds float, ptr [[TMP58]], i32 0
; CHECK-NEXT:    [[TMP60:%.*]] = getelementptr inbounds float, ptr [[TMP58]], i32 4
; CHECK-NEXT:    [[WIDE_LOAD9:%.*]] = load <4 x float>, ptr [[TMP59]], align 4
; CHECK-NEXT:    [[WIDE_LOAD10:%.*]] = load <4 x float>, ptr [[TMP60]], align 4
; CHECK-NEXT:    [[TMP61:%.*]] = fmul fast <4 x float> [[TMP56]], [[WIDE_LOAD9]]
; CHECK-NEXT:    [[TMP62:%.*]] = fmul fast <4 x float> [[TMP57]], [[WIDE_LOAD10]]
; CHECK-NEXT:    [[TMP63:%.*]] = getelementptr inbounds [512 x float], ptr @kernel4, i64 0, i64 [[TMP0]]
; CHECK-NEXT:    [[TMP64:%.*]] = getelementptr inbounds float, ptr [[TMP63]], i32 0
; CHECK-NEXT:    [[TMP65:%.*]] = getelementptr inbounds float, ptr [[TMP63]], i32 4
; CHECK-NEXT:    [[WIDE_LOAD11:%.*]] = load <4 x float>, ptr [[TMP64]], align 4
; CHECK-NEXT:    [[WIDE_LOAD12:%.*]] = load <4 x float>, ptr [[TMP65]], align 4
; CHECK-NEXT:    [[TMP66:%.*]] = fmul fast <4 x float> [[TMP61]], [[WIDE_LOAD11]]
; CHECK-NEXT:    [[TMP67:%.*]] = fmul fast <4 x float> [[TMP62]], [[WIDE_LOAD12]]
; CHECK-NEXT:    [[TMP68]] = fadd fast <4 x float> [[VEC_PHI]], [[TMP66]]
; CHECK-NEXT:    [[TMP69]] = fadd fast <4 x float> [[VEC_PHI1]], [[TMP67]]
; CHECK-NEXT:    [[TMP70:%.*]] = add i64 [[TMP16]], 1
; CHECK-NEXT:    [[TMP71:%.*]] = add i64 [[TMP17]], 1
; CHECK-NEXT:    [[TMP72:%.*]] = add i64 [[TMP18]], 1
; CHECK-NEXT:    [[TMP73:%.*]] = add i64 [[TMP19]], 1
; CHECK-NEXT:    [[TMP74:%.*]] = add i64 [[TMP20]], 1
; CHECK-NEXT:    [[TMP75:%.*]] = add i64 [[TMP21]], 1
; CHECK-NEXT:    [[TMP76:%.*]] = add i64 [[TMP22]], 1
; CHECK-NEXT:    [[TMP77:%.*]] = add i64 [[TMP23]], 1
; CHECK-NEXT:    [[TMP78:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP70]]
; CHECK-NEXT:    [[TMP79:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP71]]
; CHECK-NEXT:    [[TMP80:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP72]]
; CHECK-NEXT:    [[TMP81:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP73]]
; CHECK-NEXT:    [[TMP82:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP74]]
; CHECK-NEXT:    [[TMP83:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP75]]
; CHECK-NEXT:    [[TMP84:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP76]]
; CHECK-NEXT:    [[TMP85:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP77]]
; CHECK-NEXT:    [[TMP86:%.*]] = load float, ptr [[TMP78]], align 4
; CHECK-NEXT:    [[TMP87:%.*]] = load float, ptr [[TMP79]], align 4
; CHECK-NEXT:    [[TMP88:%.*]] = load float, ptr [[TMP80]], align 4
; CHECK-NEXT:    [[TMP89:%.*]] = load float, ptr [[TMP81]], align 4
; CHECK-NEXT:    [[TMP90:%.*]] = insertelement <4 x float> poison, float [[TMP86]], i32 0
; CHECK-NEXT:    [[TMP91:%.*]] = insertelement <4 x float> [[TMP90]], float [[TMP87]], i32 1
; CHECK-NEXT:    [[TMP92:%.*]] = insertelement <4 x float> [[TMP91]], float [[TMP88]], i32 2
; CHECK-NEXT:    [[TMP93:%.*]] = insertelement <4 x float> [[TMP92]], float [[TMP89]], i32 3
; CHECK-NEXT:    [[TMP94:%.*]] = load float, ptr [[TMP82]], align 4
; CHECK-NEXT:    [[TMP95:%.*]] = load float, ptr [[TMP83]], align 4
; CHECK-NEXT:    [[TMP96:%.*]] = load float, ptr [[TMP84]], align 4
; CHECK-NEXT:    [[TMP97:%.*]] = load float, ptr [[TMP85]], align 4
; CHECK-NEXT:    [[TMP98:%.*]] = insertelement <4 x float> poison, float [[TMP94]], i32 0
; CHECK-NEXT:    [[TMP99:%.*]] = insertelement <4 x float> [[TMP98]], float [[TMP95]], i32 1
; CHECK-NEXT:    [[TMP100:%.*]] = insertelement <4 x float> [[TMP99]], float [[TMP96]], i32 2
; CHECK-NEXT:    [[TMP101:%.*]] = insertelement <4 x float> [[TMP100]], float [[TMP97]], i32 3
; CHECK-NEXT:    [[TMP102:%.*]] = fmul fast <4 x float> [[WIDE_LOAD]], [[TMP93]]
; CHECK-NEXT:    [[TMP103:%.*]] = fmul fast <4 x float> [[WIDE_LOAD6]], [[TMP101]]
; CHECK-NEXT:    [[TMP104:%.*]] = fmul fast <4 x float> [[WIDE_LOAD7]], [[TMP102]]
; CHECK-NEXT:    [[TMP105:%.*]] = fmul fast <4 x float> [[WIDE_LOAD8]], [[TMP103]]
; CHECK-NEXT:    [[TMP106:%.*]] = fmul fast <4 x float> [[WIDE_LOAD9]], [[TMP104]]
; CHECK-NEXT:    [[TMP107:%.*]] = fmul fast <4 x float> [[WIDE_LOAD10]], [[TMP105]]
; CHECK-NEXT:    [[TMP108:%.*]] = fmul fast <4 x float> [[WIDE_LOAD11]], [[TMP106]]
; CHECK-NEXT:    [[TMP109:%.*]] = fmul fast <4 x float> [[WIDE_LOAD12]], [[TMP107]]
; CHECK-NEXT:    [[TMP110]] = fadd fast <4 x float> [[VEC_PHI2]], [[TMP108]]
; CHECK-NEXT:    [[TMP111]] = fadd fast <4 x float> [[VEC_PHI3]], [[TMP109]]
; CHECK-NEXT:    [[TMP112:%.*]] = add i64 [[TMP16]], 2
; CHECK-NEXT:    [[TMP113:%.*]] = add i64 [[TMP17]], 2
; CHECK-NEXT:    [[TMP114:%.*]] = add i64 [[TMP18]], 2
; CHECK-NEXT:    [[TMP115:%.*]] = add i64 [[TMP19]], 2
; CHECK-NEXT:    [[TMP116:%.*]] = add i64 [[TMP20]], 2
; CHECK-NEXT:    [[TMP117:%.*]] = add i64 [[TMP21]], 2
; CHECK-NEXT:    [[TMP118:%.*]] = add i64 [[TMP22]], 2
; CHECK-NEXT:    [[TMP119:%.*]] = add i64 [[TMP23]], 2
; CHECK-NEXT:    [[TMP120:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP112]]
; CHECK-NEXT:    [[TMP121:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP113]]
; CHECK-NEXT:    [[TMP122:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP114]]
; CHECK-NEXT:    [[TMP123:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP115]]
; CHECK-NEXT:    [[TMP124:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP116]]
; CHECK-NEXT:    [[TMP125:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP117]]
; CHECK-NEXT:    [[TMP126:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP118]]
; CHECK-NEXT:    [[TMP127:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[TMP119]]
; CHECK-NEXT:    [[TMP128:%.*]] = load float, ptr [[TMP120]], align 4
; CHECK-NEXT:    [[TMP129:%.*]] = load float, ptr [[TMP121]], align 4
; CHECK-NEXT:    [[TMP130:%.*]] = load float, ptr [[TMP122]], align 4
; CHECK-NEXT:    [[TMP131:%.*]] = load float, ptr [[TMP123]], align 4
; CHECK-NEXT:    [[TMP132:%.*]] = insertelement <4 x float> poison, float [[TMP128]], i32 0
; CHECK-NEXT:    [[TMP133:%.*]] = insertelement <4 x float> [[TMP132]], float [[TMP129]], i32 1
; CHECK-NEXT:    [[TMP134:%.*]] = insertelement <4 x float> [[TMP133]], float [[TMP130]], i32 2
; CHECK-NEXT:    [[TMP135:%.*]] = insertelement <4 x float> [[TMP134]], float [[TMP131]], i32 3
; CHECK-NEXT:    [[TMP136:%.*]] = load float, ptr [[TMP124]], align 4
; CHECK-NEXT:    [[TMP137:%.*]] = load float, ptr [[TMP125]], align 4
; CHECK-NEXT:    [[TMP138:%.*]] = load float, ptr [[TMP126]], align 4
; CHECK-NEXT:    [[TMP139:%.*]] = load float, ptr [[TMP127]], align 4
; CHECK-NEXT:    [[TMP140:%.*]] = insertelement <4 x float> poison, float [[TMP136]], i32 0
; CHECK-NEXT:    [[TMP141:%.*]] = insertelement <4 x float> [[TMP140]], float [[TMP137]], i32 1
; CHECK-NEXT:    [[TMP142:%.*]] = insertelement <4 x float> [[TMP141]], float [[TMP138]], i32 2
; CHECK-NEXT:    [[TMP143:%.*]] = insertelement <4 x float> [[TMP142]], float [[TMP139]], i32 3
; CHECK-NEXT:    [[TMP144:%.*]] = fmul fast <4 x float> [[WIDE_LOAD]], [[TMP135]]
; CHECK-NEXT:    [[TMP145:%.*]] = fmul fast <4 x float> [[WIDE_LOAD6]], [[TMP143]]
; CHECK-NEXT:    [[TMP146:%.*]] = fmul fast <4 x float> [[WIDE_LOAD7]], [[TMP144]]
; CHECK-NEXT:    [[TMP147:%.*]] = fmul fast <4 x float> [[WIDE_LOAD8]], [[TMP145]]
; CHECK-NEXT:    [[TMP148:%.*]] = fmul fast <4 x float> [[WIDE_LOAD9]], [[TMP146]]
; CHECK-NEXT:    [[TMP149:%.*]] = fmul fast <4 x float> [[WIDE_LOAD10]], [[TMP147]]
; CHECK-NEXT:    [[TMP150:%.*]] = fmul fast <4 x float> [[WIDE_LOAD11]], [[TMP148]]
; CHECK-NEXT:    [[TMP151:%.*]] = fmul fast <4 x float> [[WIDE_LOAD12]], [[TMP149]]
; CHECK-NEXT:    [[TMP152]] = fadd fast <4 x float> [[VEC_PHI4]], [[TMP150]]
; CHECK-NEXT:    [[TMP153]] = fadd fast <4 x float> [[VEC_PHI5]], [[TMP151]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; CHECK-NEXT:    [[TMP154:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP154]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[BIN_RDX:%.*]] = fadd fast <4 x float> [[TMP69]], [[TMP68]]
; CHECK-NEXT:    [[TMP155:%.*]] = call fast float @llvm.vector.reduce.fadd.v4f32(float 0.000000e+00, <4 x float> [[BIN_RDX]])
; CHECK-NEXT:    [[BIN_RDX13:%.*]] = fadd fast <4 x float> [[TMP111]], [[TMP110]]
; CHECK-NEXT:    [[TMP156:%.*]] = call fast float @llvm.vector.reduce.fadd.v4f32(float 0.000000e+00, <4 x float> [[BIN_RDX13]])
; CHECK-NEXT:    [[BIN_RDX14:%.*]] = fadd fast <4 x float> [[TMP153]], [[TMP152]]
; CHECK-NEXT:    [[TMP157:%.*]] = call fast float @llvm.vector.reduce.fadd.v4f32(float 0.000000e+00, <4 x float> [[BIN_RDX14]])
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[SIZE]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_FOR_END_CRIT_EDGE:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_MERGE_RDX:%.*]] = phi float [ [[TMP155]], %[[MIDDLE_BLOCK]] ], [ 0.000000e+00, %[[FOR_BODY_LR_PH]] ]
; CHECK-NEXT:    [[BC_MERGE_RDX15:%.*]] = phi float [ [[TMP156]], %[[MIDDLE_BLOCK]] ], [ 0.000000e+00, %[[FOR_BODY_LR_PH]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[FOR_BODY_LR_PH]] ]
; CHECK-NEXT:    [[BC_MERGE_RDX16:%.*]] = phi float [ [[TMP157]], %[[MIDDLE_BLOCK]] ], [ 0.000000e+00, %[[FOR_BODY_LR_PH]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[R_057:%.*]] = phi float [ [[BC_MERGE_RDX]], %[[SCALAR_PH]] ], [ [[ADD10:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[G_056:%.*]] = phi float [ [[BC_MERGE_RDX15]], %[[SCALAR_PH]] ], [ [[ADD20:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[V_055:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INC:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[B_054:%.*]] = phi float [ [[BC_MERGE_RDX16]], %[[SCALAR_PH]] ], [ [[ADD30:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ADD:%.*]] = add i64 [[V_055]], [[OFFSET]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i64 [[ADD]], 3
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[MUL]]
; CHECK-NEXT:    [[TMP158:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds [512 x float], ptr @kernel, i64 0, i64 [[V_055]]
; CHECK-NEXT:    [[TMP159:%.*]] = load float, ptr [[ARRAYIDX2]], align 4
; CHECK-NEXT:    [[MUL3:%.*]] = fmul fast float [[TMP158]], [[TMP159]]
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds [512 x float], ptr @kernel2, i64 0, i64 [[V_055]]
; CHECK-NEXT:    [[TMP160:%.*]] = load float, ptr [[ARRAYIDX4]], align 4
; CHECK-NEXT:    [[MUL5:%.*]] = fmul fast float [[MUL3]], [[TMP160]]
; CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds [512 x float], ptr @kernel3, i64 0, i64 [[V_055]]
; CHECK-NEXT:    [[TMP161:%.*]] = load float, ptr [[ARRAYIDX6]], align 4
; CHECK-NEXT:    [[MUL7:%.*]] = fmul fast float [[MUL5]], [[TMP161]]
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds [512 x float], ptr @kernel4, i64 0, i64 [[V_055]]
; CHECK-NEXT:    [[TMP162:%.*]] = load float, ptr [[ARRAYIDX8]], align 4
; CHECK-NEXT:    [[MUL9:%.*]] = fmul fast float [[MUL7]], [[TMP162]]
; CHECK-NEXT:    [[ADD10]] = fadd fast float [[R_057]], [[MUL9]]
; CHECK-NEXT:    [[ARRAYIDX_SUM:%.*]] = add i64 [[MUL]], 1
; CHECK-NEXT:    [[ARRAYIDX11:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[ARRAYIDX_SUM]]
; CHECK-NEXT:    [[TMP163:%.*]] = load float, ptr [[ARRAYIDX11]], align 4
; CHECK-NEXT:    [[MUL13:%.*]] = fmul fast float [[TMP159]], [[TMP163]]
; CHECK-NEXT:    [[MUL15:%.*]] = fmul fast float [[TMP160]], [[MUL13]]
; CHECK-NEXT:    [[MUL17:%.*]] = fmul fast float [[TMP161]], [[MUL15]]
; CHECK-NEXT:    [[MUL19:%.*]] = fmul fast float [[TMP162]], [[MUL17]]
; CHECK-NEXT:    [[ADD20]] = fadd fast float [[G_056]], [[MUL19]]
; CHECK-NEXT:    [[ARRAYIDX_SUM52:%.*]] = add i64 [[MUL]], 2
; CHECK-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 [[ARRAYIDX_SUM52]]
; CHECK-NEXT:    [[TMP164:%.*]] = load float, ptr [[ARRAYIDX21]], align 4
; CHECK-NEXT:    [[MUL23:%.*]] = fmul fast float [[TMP159]], [[TMP164]]
; CHECK-NEXT:    [[MUL25:%.*]] = fmul fast float [[TMP160]], [[MUL23]]
; CHECK-NEXT:    [[MUL27:%.*]] = fmul fast float [[TMP161]], [[MUL25]]
; CHECK-NEXT:    [[MUL29:%.*]] = fmul fast float [[TMP162]], [[MUL27]]
; CHECK-NEXT:    [[ADD30]] = fadd fast float [[B_054]], [[MUL29]]
; CHECK-NEXT:    [[INC]] = add i64 [[V_055]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INC]], [[SIZE]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[FOR_BODY]], label %[[FOR_COND_FOR_END_CRIT_EDGE]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[FOR_COND_FOR_END_CRIT_EDGE]]:
; CHECK-NEXT:    [[ADD30_LCSSA:%.*]] = phi float [ [[ADD30]], %[[FOR_BODY]] ], [ [[TMP157]], %[[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    [[ADD20_LCSSA:%.*]] = phi float [ [[ADD20]], %[[FOR_BODY]] ], [ [[TMP156]], %[[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    [[ADD10_LCSSA:%.*]] = phi float [ [[ADD10]], %[[FOR_BODY]] ], [ [[TMP155]], %[[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    [[PHITMP:%.*]] = fptoui float [[ADD10_LCSSA]] to i8
; CHECK-NEXT:    [[PHITMP60:%.*]] = fptoui float [[ADD20_LCSSA]] to i8
; CHECK-NEXT:    [[PHITMP61:%.*]] = fptoui float [[ADD30_LCSSA]] to i8
; CHECK-NEXT:    br label %[[FOR_END]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    [[R_0_LCSSA:%.*]] = phi i8 [ [[PHITMP]], %[[FOR_COND_FOR_END_CRIT_EDGE]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[G_0_LCSSA:%.*]] = phi i8 [ [[PHITMP60]], %[[FOR_COND_FOR_END_CRIT_EDGE]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[B_0_LCSSA:%.*]] = phi i8 [ [[PHITMP61]], %[[FOR_COND_FOR_END_CRIT_EDGE]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    store i8 [[R_0_LCSSA]], ptr @r_, align 1
; CHECK-NEXT:    store i8 [[G_0_LCSSA]], ptr @g_, align 1
; CHECK-NEXT:    store i8 [[B_0_LCSSA]], ptr @b_, align 1
; CHECK-NEXT:    ret void
;
entry:
  %cmp53 = icmp eq i64 %size, 0
  br i1 %cmp53, label %for.end, label %for.body.lr.ph

for.body.lr.ph:
  br label %for.body

for.body:
  %r.057 = phi float [ 0.000000e+00, %for.body.lr.ph ], [ %add10, %for.body ]
  %g.056 = phi float [ 0.000000e+00, %for.body.lr.ph ], [ %add20, %for.body ]
  %v.055 = phi i64 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %b.054 = phi float [ 0.000000e+00, %for.body.lr.ph ], [ %add30, %for.body ]
  %add = add i64 %v.055, %offset
  %mul = mul i64 %add, 3
  %arrayidx = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 %mul
  %0 = load float, ptr %arrayidx, align 4
  %arrayidx2 = getelementptr inbounds [512 x float], ptr @kernel, i64 0, i64 %v.055
  %1 = load float, ptr %arrayidx2, align 4
  %mul3 = fmul fast float %0, %1
  %arrayidx4 = getelementptr inbounds [512 x float], ptr @kernel2, i64 0, i64 %v.055
  %2 = load float, ptr %arrayidx4, align 4
  %mul5 = fmul fast float %mul3, %2
  %arrayidx6 = getelementptr inbounds [512 x float], ptr @kernel3, i64 0, i64 %v.055
  %3 = load float, ptr %arrayidx6, align 4
  %mul7 = fmul fast float %mul5, %3
  %arrayidx8 = getelementptr inbounds [512 x float], ptr @kernel4, i64 0, i64 %v.055
  %4 = load float, ptr %arrayidx8, align 4
  %mul9 = fmul fast float %mul7, %4
  %add10 = fadd fast float %r.057, %mul9
  %arrayidx.sum = add i64 %mul, 1
  %arrayidx11 = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 %arrayidx.sum
  %5 = load float, ptr %arrayidx11, align 4
  %mul13 = fmul fast float %1, %5
  %mul15 = fmul fast float %2, %mul13
  %mul17 = fmul fast float %3, %mul15
  %mul19 = fmul fast float %4, %mul17
  %add20 = fadd fast float %g.056, %mul19
  %arrayidx.sum52 = add i64 %mul, 2
  %arrayidx21 = getelementptr inbounds [1536 x float], ptr @src_data, i64 0, i64 %arrayidx.sum52
  %6 = load float, ptr %arrayidx21, align 4
  %mul23 = fmul fast float %1, %6
  %mul25 = fmul fast float %2, %mul23
  %mul27 = fmul fast float %3, %mul25
  %mul29 = fmul fast float %4, %mul27
  %add30 = fadd fast float %b.054, %mul29
  %inc = add i64 %v.055, 1
  %exitcond = icmp ne i64 %inc, %size
  br i1 %exitcond, label %for.body, label %for.cond.for.end_crit_edge

for.cond.for.end_crit_edge:
  %add30.lcssa = phi float [ %add30, %for.body ]
  %add20.lcssa = phi float [ %add20, %for.body ]
  %add10.lcssa = phi float [ %add10, %for.body ]
  %phitmp = fptoui float %add10.lcssa to i8
  %phitmp60 = fptoui float %add20.lcssa to i8
  %phitmp61 = fptoui float %add30.lcssa to i8
  br label %for.end

for.end:
  %r.0.lcssa = phi i8 [ %phitmp, %for.cond.for.end_crit_edge ], [ 0, %entry ]
  %g.0.lcssa = phi i8 [ %phitmp60, %for.cond.for.end_crit_edge ], [ 0, %entry ]
  %b.0.lcssa = phi i8 [ %phitmp61, %for.cond.for.end_crit_edge ], [ 0, %entry ]
  store i8 %r.0.lcssa, ptr @r_, align 1
  store i8 %g.0.lcssa, ptr @g_, align 1
  store i8 %b.0.lcssa, ptr @b_, align 1
  ret void
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
;.
